updated set -e

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -2,28 +2,66 @@ name: Deploy Application
 
 on:
   push:
-      branches:
-        - main
+    branches:
+      - main
+
 env:
   HOSTNAME: flask-lms
 
 jobs:
-    server-ec2-test:
-        runs-on: ubuntu-latest
-        steps:
-          - name: Execute Commands on EC2
-            uses: appleboy/ssh-action@v1.0.3
 
-            with:
-                host: ${{secrets.SERVER_HOST}}
-                username: ubuntu
-                key: ${{secrets.SERVER_SSH_KEY}}
-                script: |
-                  set -e
-                  echo "Connected to EC2 ✅"
-                  
-                  python3 --version
-                  docker --version
-                  df -h
-                  sudo hostnamectl set-hostname "${{ env.HOSTNAME }}"
-                  echo "Current Hostname: $(hostname)"
+  server-setup-and-test:
+
+    runs-on: ubuntu-latest
+
+    steps:
+
+      - name: Execute Commands on EC2
+
+        uses: appleboy/ssh-action@v1.0.3
+
+        with:
+          host: ${{ secrets.SERVER_HOST }}
+          username: ubuntu
+          key: ${{ secrets.SERVER_SSH_KEY }}
+
+          script: |
+
+            set -e
+
+            echo "Connected to EC2 ✅"
+
+            echo "Updating packages..."
+            sudo apt update -y
+
+            echo "Checking Docker installation..."
+
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found. Installing Docker..."
+
+              sudo apt install docker.io -y
+
+              sudo systemctl enable docker
+              sudo systemctl start docker
+
+              sudo usermod -aG docker ubuntu
+
+              echo "Docker installed successfully ✅"
+
+            else
+              echo "Docker already installed ✅"
+            fi
+
+            echo "Docker Version:"
+            docker --version
+
+            echo "Python Version:"
+            python3 --version
+
+            echo "Disk Usage:"
+            df -h
+
+            sudo hostnamectl set-hostname "${{ env.HOSTNAME }}"
+
+            echo "Current Hostname: $(hostname)"
